---
layout: post
title: 예외처리
categories: java
tags: [java]
---

예외처리
================

예외
--------------------
+ 프로그래밍에서 예외(Exception)란 입력 값에 대한 처리가 불가능하거나, 프로그램 실행 중에 참조된 값이 잘못된 경우 등 정상적인 프로그램의 흐름을 어긋나는 것을 말한다. 
+ 자바에서 예외는 개발자가 직접 처리할 수 있기 때문에 예외 상황을 미리 예측하여 핸들링할 수 있다.
+ 한편, 에러(Error)는 시스템에 무엇인가 비정상적인 상황이 발생한 경우에 사용된다. 
+ 주로 자바 가상머신에서 발생시키는 것이며 예외와 반대로 이를 애플리케이션 코드에서 잡으려고 하면 안 된다. 
+ 에러의 예로는 OutOfMemoryError, ThreadDeath, StackOverflowError 등이 있다.

Checked 와 Unchecked Exception
----------------------------
+ Exception은 Checked Exception과 Unchecked Exception으로 구분할 수 있다.
+ 간단하게 RuntimeException을 상속하지 않는 클래스는 Checked Exception, 반대로 상속한 클래스는 Unchecked Exception으로 분류할 수 있다.
+ 여기서 RuntimeException은 Exception 클래스의 서브 클래스이기 때문에 Exception의 일종이기도 하지만 자바에서는 RuntimeException과 이를 상속한 클래스를 조금 특별하게 취급한다.

=>자바에서 예외는 RuntimeException을 상속하지 않고 꼭 처리해야 하는 Checked Exception과 반대로 명시적으로 처리하지 않아도 되는 Unchecked Exception으로 구분 가능

예외 처리하기
-----------------
+ 예외를 처리하는 방법에는예외 복구, 예외 처리 회피 , 예외 전환 방법이 있다.
---------------------------------------------------------
1. 예외 복구
+ 예외 상황을 파악하고 문제를 해결해서 정상 상태로 돌려놓는 방법
+ 예외를 잡아서 일정시간, 조건만큼 대기하고 다시 재시도를 반복
+ 최대 재시도 횟수를 넘기게 되는 경우 예외를 발생시킴
------------------------------------------------------
2. 예외 처리 회피
+ 예외 처리를 직접 담당하지 않고 호출한 쪽으로 던져 회피하는 방법
+ 그래도 예외 처리의 필요성이 있다면 어는 정도는 처리하고 던지는 것이 좋음
+ 긴밀하게 역할을 분반담하고 있는 관가 아니라면 예외를 그냥 던지면 무책임
-----------------------------------------------------
3. 예외 전환
+ 예외 회피와 비슷하게 메서드 밖으로 예외를 던지지만, 그냥 던지지 않고 적절한 예외로 전환해서 넘기는 방법
+ 조금 더 명확한 의미로 전달되기 위해 적합한 의미를 가진 예외로 변경
+ 예외 처리를 단순하게 만들기 위해 포장(wrap) 할 수도 있다.
-----------------------------------------------------------
try catch 문
```java
try{
    ...
}
catch(예외1){
    ...
}
catch(예외2){
    ...
}
```
+ try문안의 수행할 문장들에서 예외가 발생하지 않는다면 catch문 다음의 문장들은 수행되지 않는다.
+ 하지만 try 문안의 문장을 수행하는 도중에 예외가 발생하면 예외에 해당하는 catch문이 시행된다.
ex)
```java
int c;
try{
    c=4/0;
}catch(AritmeticException e){
    c = -1;
}
```
+ ArithmeticException e에서 e는 ArithmeticException 클래스의 객체, 즉 오류 객체에 해당한다.
+ 이 오류 객체를 통해 예외 클래스의 메서드를 호출할 수 있다.

finally
---------------------
+ 프로그램 수행 도중 예외가 발생하면 프로그램이 중지되거나 예외 처리에 의해 catch 구문이 실행된다.
+ finally 구문은 try 문장 수행 중 예외발생 여부에 상관없이 무조건 실행된다.
ex)
```java
public class Sample {
    public void shouldBeRun() {
        System.out.println("ok thanks.");
    }

    public static void main(String[] args) {
        Sample sample = new Sample();
        int c;
        try {
            c = 4 / 0;
        } catch (ArithmeticException e) {
            c = -1;
        } finally {
            sample.shouldBeRun();
        }
    }
}
```

예외 던지기(throws)
--------------------------------
```java
class FoolException extends Exception {
}

public class Sample {
    public void sayNick(String nick) throws FoolException {
        if("fool".equals(nick)) {
            throw new FoolException();
        }
        System.out.println("당신의 별명은 "+nick+" 입니다.");
    }

    public static void main(String[] args) {
        Sample sample = new Sample();
        try {
            sample.sayNick("fool");
            sample.sayNick("genious");
        } catch (FoolException e) {
            System.err.println("FoolException이 발생했습니다.");
        }
    }
}
```
+ say nick 메소드 뒷부분애 throws 라는 구문을 이용하여 FoolException을 위로 보낼 수 있음
